### ISSUE TITLE
Why GPL License?

### ISSUE THREAD

**Issue by karli2000** [GravyDev/grunt-codedeploy#1]
Hi,

we would love to use this module but with a GPL license it is impossible to use this in a commercial environment. What is the reason that you use this license?

**Comment by dainbrump** [comment]
We honestly did not expect a lot of traffic for this module, let alone traffic in terms of commercial use in applications for sale and GPL was a default choice in the generator we used. We have updates that will be pushed soon and and will address the license issue then. Because we are beginning to see more interest for commercial environments, we will be switching to an MIT license for this module.

**Comment by karli2000** [comment]
Great! And keep up the good work!
